package Lexer;

/* Generated By:JavaCC: Do not edit this line. IncognitoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface IncognitoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 5;
  /** RegularExpression Id. */
  int ELSE = 6;
  /** RegularExpression Id. */
  int WHILE = 7;
  /** RegularExpression Id. */
  int PUBLIC = 8;
  /** RegularExpression Id. */
  int MAIN = 9;
  /** RegularExpression Id. */
  int CLASS = 10;
  /** RegularExpression Id. */
  int EXTENDS = 11;
  /** RegularExpression Id. */
  int RETURN = 12;
  /** RegularExpression Id. */
  int PRINT = 13;
  /** RegularExpression Id. */
  int LENGTH = 14;
  /** RegularExpression Id. */
  int NEW = 15;
  /** RegularExpression Id. */
  int THIS = 16;
  /** RegularExpression Id. */
  int BOOLEAN = 17;
  /** RegularExpression Id. */
  int INT = 18;
  /** RegularExpression Id. */
  int TRUE = 19;
  /** RegularExpression Id. */
  int FALSE = 20;
  /** RegularExpression Id. */
  int EXCLAMATION = 21;
  /** RegularExpression Id. */
  int STRING_ARRAY = 22;
  /** RegularExpression Id. */
  int INT_ARRAY = 23;
  /** RegularExpression Id. */
  int L_PARENTHESIS = 24;
  /** RegularExpression Id. */
  int R_PARENTHESIS = 25;
  /** RegularExpression Id. */
  int LCURLYBRACE = 26;
  /** RegularExpression Id. */
  int RCURLYBRACE = 27;
  /** RegularExpression Id. */
  int LSQUAREBRACKET = 28;
  /** RegularExpression Id. */
  int RSQUAREBRACKET = 29;
  /** RegularExpression Id. */
  int SEMICOLON = 30;
  /** RegularExpression Id. */
  int COMMA = 31;
  /** RegularExpression Id. */
  int DOT = 32;
  /** RegularExpression Id. */
  int AND = 33;
  /** RegularExpression Id. */
  int LESS_THAN = 34;
  /** RegularExpression Id. */
  int PLUS = 35;
  /** RegularExpression Id. */
  int MINUS = 36;
  /** RegularExpression Id. */
  int STAR = 37;
  /** RegularExpression Id. */
  int ASSIGNEQUAL = 38;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 39;
  /** RegularExpression Id. */
  int ID = 40;
  /** RegularExpression Id. */
  int DIGIT = 41;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"public\"",
    "\"public static void main\"",
    "\"class\"",
    "\"extends\"",
    "\"return\"",
    "\"System.out.println\"",
    "\"length\"",
    "\"new\"",
    "\"this\"",
    "\"boolean\"",
    "\"int\"",
    "\"true\"",
    "\"false\"",
    "\"!\"",
    "<STRING_ARRAY>",
    "<INT_ARRAY>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"&&\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"=\"",
    "<INTEGER_LITERAL>",
    "<ID>",
    "<DIGIT>",
  };

}
